# Generated by Django 3.1.6 on 2021-03-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Firstname', models.TextField(max_length=20)),
                ('Lastname', models.TextField(max_length=20)),
                ('gender', models.TextField()),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('remember_me', models.BooleanField(blank=True, default=True, null=True)),
                ('profilePicture', models.ImageField(blank=True, default='img/profile_img/default.jpg', height_field='heightfield', null=True, upload_to='', width_field='widthfield')),
                ('heightfield', models.IntegerField(default=0)),
                ('widthfield', models.IntegerField(default=0)),
            ],
        ),
    ]
