# Generated by Django 3.1.6 on 2021-02-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210220_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsdb',
            name='remember_me',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
