# Generated by Django 3.1.5 on 2021-01-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoApp_Fields',
            fields=[
                ('activity', models.TextField(primary_key=True, serialize=False)),
                ('createTime', models.TimeField(auto_now_add=True)),
                ('urgency', models.IntegerField(null=True)),
            ],
        ),
    ]
