# Generated by Django 3.1.5 on 2021-02-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210201_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoapp_fields',
            name='DueDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='todoapp_fields',
            name='createTime',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
