# Generated by Django 3.1.5 on 2021-02-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20210201_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoapp_fields',
            name='DueDate',
            field=models.DateField(null=True),
        ),
    ]
