# Generated by Django 3.0.5 on 2021-02-13 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20210213_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoapp_fields',
            old_name='taskID',
            new_name='task_id',
        ),
    ]
