# Generated by Django 3.0.5 on 2021-02-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20210213_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoapp_fields',
            name='task_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
