# Generated by Django 3.0.5 on 2021-02-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20210213_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoapp_fields',
            name='task_id',
        ),
        migrations.AddField(
            model_name='todoapp_fields',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
